#############################################################################
# Makefile for building: opencv.app/Contents/MacOS/opencv
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  opencv.pro
# Template: app
# Command: /Users/jameshook/Qt/5.12.3/clang_64/bin/qmake -o Makefile opencv.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv4 -I../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtQml.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtNetwork.framework/Headers -I../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode10.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I../../Qt/5.12.3/clang_64/mkspecs/macx-clang -F/Users/jameshook/Qt/5.12.3/clang_64/lib
QMAKE         = /Users/jameshook/Qt/5.12.3/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/jameshook/Qt/5.12.3/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/jameshook/Qt/5.12.3/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = opencv1.0.0
DISTDIR = /Users/jameshook/opencv/OpenCVQml/.tmp/opencv1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/jameshook/Qt/5.12.3/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jameshook/Qt/5.12.3/clang_64/lib -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_imgcodecs -framework QtQuick -framework QtGui -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = blur.cpp \
		linearfilter.cpp \
		main.cpp \
		mat.cpp qrc_qml.cpp \
		moc_blur.cpp \
		moc_linearfilter.cpp \
		moc_mat.cpp
OBJECTS       = blur.o \
		linearfilter.o \
		main.o \
		mat.o \
		qrc_qml.o \
		moc_blur.o \
		moc_linearfilter.o \
		moc_mat.o
DIST          = README.md \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf \
		opencv.pro blur.h \
		linearfilter.h \
		mat.h blur.cpp \
		linearfilter.cpp \
		main.cpp \
		mat.cpp
QMAKE_TARGET  = opencv
DESTDIR       = 
TARGET        = opencv.app/Contents/MacOS/opencv

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/jameshook/opencv/OpenCVQml/opencv.pro


include /Users/jameshook/Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

opencv.app/Contents/MacOS/opencv:  $(OBJECTS)  
	@test -d opencv.app/Contents/MacOS/ || mkdir -p opencv.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: opencv.pro ../../Qt/5.12.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.12.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf \
		opencv.pro \
		qml.qrc \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.12.3/clang_64/lib/QtQml.framework/QtQml.prl \
		../../Qt/5.12.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile opencv.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt/5.12.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.12.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/clang.conf:
../../Qt/5.12.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.12.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.12.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.12.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.12.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.12.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/mac.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.12.3/clang_64/mkspecs/features/lex.prf:
opencv.pro:
qml.qrc:
../../Qt/5.12.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../Qt/5.12.3/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.12.3/clang_64/lib/QtQml.framework/QtQml.prl:
../../Qt/5.12.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../Qt/5.12.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile opencv.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

opencv.app/Contents/PkgInfo: 
	@test -d opencv.app/Contents || mkdir -p opencv.app/Contents
	@$(DEL_FILE) opencv.app/Contents/PkgInfo
	@echo "APPL????" > opencv.app/Contents/PkgInfo
opencv.app/Contents/Resources/empty.lproj: 
	@test -d opencv.app/Contents/Resources || mkdir -p opencv.app/Contents/Resources
	@touch opencv.app/Contents/Resources/empty.lproj
	
opencv.app/Contents/Info.plist: 
	@test -d opencv.app/Contents || mkdir -p opencv.app/Contents
	@$(DEL_FILE) opencv.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.hempnall.opencv,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.hempnall.opencv,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,opencv,g" -e "s,@LIBRARY@,opencv,g" -e "s,\$${EXECUTABLE_NAME},opencv,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt/5.12.3/clang_64/mkspecs/macx-clang/Info.plist.app >opencv.app/Contents/Info.plist

all: Makefile \
		opencv.app/Contents/PkgInfo \
		opencv.app/Contents/Resources/empty.lproj \
		opencv.app/Contents/Info.plist opencv.app/Contents/MacOS/opencv

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents blur.h linearfilter.h mat.h $(DISTDIR)/
	$(COPY_FILE) --parents blur.cpp linearfilter.cpp main.cpp mat.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r opencv.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../Qt/5.12.3/clang_64/bin/rcc \
		main.qml
	/Users/jameshook/Qt/5.12.3/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.12.3/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_blur.cpp moc_linearfilter.cpp moc_mat.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_blur.cpp moc_linearfilter.cpp moc_mat.cpp
moc_blur.cpp: blur.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/highgui.hpp \
		/usr/local/include/opencv4/opencv2/videoio.hpp \
		linearfilter.h \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		moc_predefs.h \
		../../Qt/5.12.3/clang_64/bin/moc
	/Users/jameshook/Qt/5.12.3/clang_64/bin/moc $(DEFINES) --include /Users/jameshook/opencv/OpenCVQml/moc_predefs.h -I/Users/jameshook/Qt/5.12.3/clang_64/mkspecs/macx-clang -I/Users/jameshook/opencv/OpenCVQml -I/usr/local/include/opencv4 -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQml.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/jameshook/Qt/5.12.3/clang_64/lib blur.h -o moc_blur.cpp

moc_linearfilter.cpp: linearfilter.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		moc_predefs.h \
		../../Qt/5.12.3/clang_64/bin/moc
	/Users/jameshook/Qt/5.12.3/clang_64/bin/moc $(DEFINES) --include /Users/jameshook/opencv/OpenCVQml/moc_predefs.h -I/Users/jameshook/Qt/5.12.3/clang_64/mkspecs/macx-clang -I/Users/jameshook/opencv/OpenCVQml -I/usr/local/include/opencv4 -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQml.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/jameshook/Qt/5.12.3/clang_64/lib linearfilter.h -o moc_linearfilter.cpp

moc_mat.cpp: mat.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv4/opencv2/core/core_c.h \
		/usr/local/include/opencv4/opencv2/core/types_c.h \
		linearfilter.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		moc_predefs.h \
		../../Qt/5.12.3/clang_64/bin/moc
	/Users/jameshook/Qt/5.12.3/clang_64/bin/moc $(DEFINES) --include /Users/jameshook/opencv/OpenCVQml/moc_predefs.h -I/Users/jameshook/Qt/5.12.3/clang_64/mkspecs/macx-clang -I/Users/jameshook/opencv/OpenCVQml -I/usr/local/include/opencv4 -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtGui.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtQml.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jameshook/Qt/5.12.3/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/jameshook/Qt/5.12.3/clang_64/lib mat.h -o moc_mat.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

blur.o: blur.cpp blur.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/highgui.hpp \
		/usr/local/include/opencv4/opencv2/videoio.hpp \
		linearfilter.h \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blur.o blur.cpp

linearfilter.o: linearfilter.cpp linearfilter.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/highgui.hpp \
		/usr/local/include/opencv4/opencv2/videoio.hpp \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/include/opencv4/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv4/opencv2/core/core_c.h \
		/usr/local/include/opencv4/opencv2/core/types_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linearfilter.o linearfilter.cpp

main.o: main.cpp ../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../Qt/5.12.3/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../Qt/5.12.3/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		mat.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv4/opencv2/core/core_c.h \
		/usr/local/include/opencv4/opencv2/core/types_c.h \
		linearfilter.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		blur.h \
		/usr/local/include/opencv4/opencv2/highgui.hpp \
		/usr/local/include/opencv4/opencv2/videoio.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mat.o: mat.cpp mat.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QImage \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt/5.12.3/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv4/opencv2/core.hpp \
		/usr/local/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv4/opencv2/core/version.hpp \
		/usr/local/include/opencv4/opencv2/core/base.hpp \
		/usr/local/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/include/opencv4/opencv2/core/check.hpp \
		/usr/local/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/include/opencv4/opencv2/core/types.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc.hpp \
		/usr/local/include/opencv4/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv4/opencv2/core/core_c.h \
		/usr/local/include/opencv4/opencv2/core/types_c.h \
		linearfilter.h \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/QQuickItem \
		../../Qt/5.12.3/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Qt/5.12.3/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mat.o mat.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_blur.o: moc_blur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blur.o moc_blur.cpp

moc_linearfilter.o: moc_linearfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linearfilter.o moc_linearfilter.cpp

moc_mat.o: moc_mat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mat.o moc_mat.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/opencv/bin || mkdir -p $(INSTALL_ROOT)/opt/opencv/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/opencv/bin/opencv.app
	
	-$(QINSTALL) opencv.app $(INSTALL_ROOT)/opt/opencv/bin/opencv.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/opencv/bin/opencv.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/opencv/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

